### ISSUE TITLE
modify data error

### ISSUE THREAD

**Issue by oleg-konovalov** [parsecsv/parsecsv-for-php#149]
Hi,
I am getting the following error when I am going to modify specific row data.
My code is 

require 'parsecsv.lib.php';
$csv = new ParseCsv\Csv();
$csv->sort_by = 'id';
$csv->parse('data.csv');
$csv->data[2] = array('id' => 2, 
                      'description' => 'task2', 
                      'category' => 'system', 
                      'type' => 'hourly', 
                      'date' => '2018-09-18', 
                      'status' => 'open', 
                      'comment' => 'This is id=2');
$csv->save();

Notice: Undefined offset: 0 in D:\wamp64\www\parsecsv-for-php-1.1.0\src\Csv.php on line 849

Warning: array_keys() expects parameter 1 to be array, null given in D:\wamp64\www\parsecsv-for-php-1.1.0\src\Csv.php on line 849

Warning: array_values() expects parameter 1 to be array, null given in D:\wamp64\www\parsecsv-for-php-1.1.0\src\Csv.php on line 852

Warning: array_intersect(): Argument #2 is not an array in D:\wamp64\www\parsecsv-for-php-1.1.0\src\Csv.php on line 858

Warning: array_intersect(): Argument #2 is not an array in D:\wamp64\www\parsecsv-for-php-1.1.0\src\Csv.php on line 863

Fatal error: Uncaught UnexpectedValueException: The specified fields do not match any titles and do not match column count. $fields was Array ( [0] => id [1] => description [2] => category [3] => type [4] => date [5] => status [6] => comment ) $titlesOnParse was in D:\wamp64\www\parsecsv-for-php-1.1.0\src\Csv.php:870 Stack trace: #0 D:\wamp64\www\parsecsv-for-php-1.1.0\src\Csv.php(805): ParseCsv\Csv->_validate_fields_for_unparse(Array) #1 D:\wamp64\www\parsecsv-for-php-1.1.0\src\Csv.php(412): ParseCsv\Csv->unparse(Array, Array, false, false) #2 D:\wamp64\www\parsecsv-for-php-1.1.0\index.php(32): ParseCsv\Csv->save() #3 {main} thrown in D:\wamp64\www\parsecsv-for-php-1.1.0\src\Csv.php on line 870

I will attach my data.csv file.

I hope your help.
![screenshot_1](https://user-images.githubusercontent.com/37531972/45664450-31603800-bb4f-11e8-9978-1313af6bef90.png)

**Comment by susgo** [comment]
Thanks and sorry for the late reply. The PR #156 will solve this issue.
